FROM node:12 AS build
WORKDIR /application
COPY . .
RUN npm install --unsafe-perm
#override with --build-arg STAGE_NAME=your_value when running docker build
ARG STAGE_NAME=dev
RUN npm run build

FROM nginx:alpine
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /application/dist /usr/share/nginx/html
